name: ignousolutionhub
description: "A powerful and user-friendly Flutter web app for IGNOUE students and solutions."
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  flutter_web_plugins:
    sdk: flutter

  # Core dependencies
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.3
  http: ^1.5.0
  uuid: ^4.5.1

  # Firebase
  firebase_core: ^4.1.0
  firebase_auth: ^6.1.0
  cloud_firestore: ^6.0.1
  firebase_storage: ^13.0.1

  # State management and architecture
  flutter_riverpod: ^2.5.1
  provider: ^6.1.5+1
  get_it: ^7.7.0

  # UI and forms
  google_fonts: ^6.3.1
  form_field_validator: ^1.1.0
  flutter_screenutil: ^5.9.3
  dropdown_search: ^6.0.1
  go_router: ^14.2.0
  responsive_builder: ^0.7.1

  # Location
  geolocator: ^14.0.2
  geocoding: ^4.0.0

  # Media
  image_picker: ^1.1.2
  lottie: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - images/error_404.gif
