name: Deploy to Firebase Hosting

on: 
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Wait for 5 minutes
        run: sleep 300 # 300 seconds = 5 minutes

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable' # or 'beta', 'master'

      - name: Install dependencies
        run: flutter pub get

      - name: Build Web
        run: flutter build web --release

      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}'
          projectId: 'ignoue-solution-point' # Replace with your Firebase Project ID
          channelId: 'live' # Deploy to the live channel
          entryPoint: 'ignou_solution' # Specify the directory where firebase.json is located
